public class GetCheckboxValue {
   // @AuraEnabled(cacheable=true)
        //Create a variable for datasheet data to enter
        // datasheet__c ds = new datasheet__c();
        // public class Selection {
        //     public String label{get; set;}
        //     public String value{get; set;}
        //     public Boolean check{get; set;}
        //     public Selection(String label, String value, Boolean check) {
        //         this.label = label;
        //         this.value = value;
        //         this.check = check;
        //     }
        // } 
            //4. Investigator Qualification/Civil Engineering Construction management system - logged in Users -checkboxes /土木施工管理技士
            //public List<Selection> investigatorQualificationErLevel{get; set;}
    
            //5. Investigator Qualification/ Surveying Qualification - logged in Users /測量資格
           // public List<Selection> investigatorQualificationMeasurement{get; set;}

            // public getCheckboxValue(){
            //     this.propertyClassificationInput = new List<Selection>();
            //     this.investigatorQualificationErLevel = new List<Selection>();


            //     Schema.DescribeFieldResult fieldResult01 = surveyDataSheets__c.investigatorQualificationErLevel__c.getDescribe();
            //     List<Schema.PicklistEntry> pickListEntry01 = fieldResult01.getPicklistValues();
            //     for(integer i=0; i<pickListEntry01.size(); i++){
            //         System.debug('investigatorQualificationErLevel' + pickListEntry01[i].getValue());
            //         Selection selection = new Selection(pickListEntry01[i].getValue(), pickListEntry01[i].getLabel(),false);
            //         this.investigatorQualificationErLevel.add(selection); 
            //         }//end bracket of pickListEntry01
            // }

}